"""
• Utlizzando Python e le funzioni di NLTK, scrivere un programma che:
    • stampi gli hapax (token con frequenza 1) del testo
    • stampi la distribuzione di hapax nel testo: |𝑉1|/|𝐶|
    • ottenga il vocabolario del testo ordinato alfabeticamente
        • Per ogni elemento del vocabolario, ne stampi frequenza assoluta e relativa nel file
    • stampi la Type-Token Ratio del testo
        • 𝑇𝑇𝑅 = |𝑉𝐶|/|𝐶|
"""







import nltk
# nltk.download('punkt_tab')
import sys


def main(argv):
    return 

if __name__ == '__main__':
    main(sys.argv[1:])